# Generated by Django 4.0 on 2022-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('objects_detected', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
            ],
        ),
    ]
